//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB3_EMP_DATA
    {
        public string EMP_ID { get; set; }
        public string EMP_STATUS { get; set; }
        public string JPN_CD { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_ENGNAME { get; set; }
        public string EMP_CHG_CD { get; set; }
        public string DEPT_NO { get; set; }
        public string DIRECT_HEAD_EMP_ID { get; set; }
        public string PJOB_CD { get; set; }
        public string PJOB_DESC { get; set; }
        public string PLANT_CD { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
