//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FB3DBEntities : DbContext
    {
        public FB3DBEntities()
            : base("name=FB3DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FB3_EMP_DATA> FB3_EMP_DATA { get; set; }
        public virtual DbSet<VW_H_DEPT_DATA> VW_H_DEPT_DATA { get; set; }
        public virtual DbSet<VW_H_DEPT_LEVEL> VW_H_DEPT_LEVEL { get; set; }
        public virtual DbSet<VW_H_EMP_DATA> VW_H_EMP_DATA { get; set; }
    }
}
