//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_CODE
    {
        public string PK_NO { get; set; }
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string NAME3 { get; set; }
        public string ANNOTATION { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public string IS_USED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
    }
}
