//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_PCRT
    {
        public string PK_NO { get; set; }
        public string EMPID { get; set; }
        public string LIC_CD { get; set; }
        public string LIC_NO { get; set; }
        public string LIC_DATE { get; set; }
        public string RE_LIC_DATE { get; set; }
        public string IS_ASSIGN { get; set; }
        public string IS_TEACHER { get; set; }
        public string IS_GRD { get; set; }
        public string GRD_NO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
    }
}
