//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_H_EMP_DATA
    {
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_ENGNAME { get; set; }
        public string EMP_STATUS { get; set; }
        public string EMP_STATUS_DESC { get; set; }
        public string EMP_CHG_CD { get; set; }
        public string EMP_CHG_DESC { get; set; }
        public Nullable<decimal> WORK_YEARS { get; set; }
        public Nullable<decimal> WORK_DAYS { get; set; }
        public Nullable<decimal> SERVICE_YEARS { get; set; }
        public Nullable<decimal> SERVICE_DAYS { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<decimal> RECENT_LEVEL_WORK_DAYS { get; set; }
        public Nullable<decimal> RECENT_PJOB_WORK_DAYS { get; set; }
        public Nullable<decimal> RECENT_DEPT_WORK_DAYS { get; set; }
        public Nullable<decimal> RECENT_DIV_WORK_DAYS { get; set; }
        public Nullable<decimal> STUDENT_WORK_DAYS { get; set; }
        public Nullable<decimal> K_WORK_DAYS { get; set; }
        public Nullable<decimal> T_WORK_DAYS { get; set; }
        public string WS_CD { get; set; }
        public string WS_DESC { get; set; }
        public string COMPANY_CD { get; set; }
        public string COMPANY_NAME { get; set; }
        public string PLANT_CD { get; set; }
        public string PLANT_NAME { get; set; }
        public string DEPT_NO { get; set; }
        public string DEPT_NAME { get; set; }
        public string DEPT_FULL_NAME { get; set; }
        public string DIV_DEPT_FULL_NAME { get; set; }
        public string DEPT_NO_20 { get; set; }
        public string DEPT_NAME_20 { get; set; }
        public string DEPT_NO_30 { get; set; }
        public string DEPT_NAME_30 { get; set; }
        public string DEPT_NO_40 { get; set; }
        public string DEPT_NAME_40 { get; set; }
        public string DEPT_NO_50 { get; set; }
        public string DEPT_NAME_50 { get; set; }
        public string DEPT_NO_60 { get; set; }
        public string DEPT_NAME_60 { get; set; }
        public string DEPT_NO_70 { get; set; }
        public string DEPT_NAME_70 { get; set; }
        public string EMP_CD { get; set; }
        public string EMP_DESC { get; set; }
        public string LEVEL_CD { get; set; }
        public string GRADE_CD { get; set; }
        public string PJOB_CD { get; set; }
        public string PJOB_DESC { get; set; }
        public string WORK_SHIFT_CD { get; set; }
        public string WORK_SHIFT_DESC { get; set; }
        public string CALENDAR_CD { get; set; }
        public string CALENDAR_DESC { get; set; }
        public string WORK_CD { get; set; }
        public string WORK_DESC { get; set; }
        public string ACC_CD { get; set; }
        public Nullable<System.DateTime> JOIN_DT { get; set; }
        public Nullable<System.DateTime> EXAM_EXPIRE_DT { get; set; }
        public Nullable<System.DateTime> LEAVE_DT { get; set; }
        public string LEAVE_REASON { get; set; }
        public string LEAVE_REASON_DESC { get; set; }
        public Nullable<System.DateTime> PLAN_RETENTION_EDT { get; set; }
        public Nullable<System.DateTime> RETENTION_EDT { get; set; }
        public string TRANSFER_REASON { get; set; }
        public string TRANSFER_REASON_DESC { get; set; }
        public Nullable<System.DateTime> TRANSFER_SDT { get; set; }
        public Nullable<System.DateTime> PLAN_TRANSFER_EDT { get; set; }
        public Nullable<System.DateTime> TRANSFER_EDT { get; set; }
        public string TRANSFER_NATION_CD { get; set; }
        public string TRANSFER_NATION_NAME { get; set; }
        public string TRANSFER_COMPANY_CD { get; set; }
        public string TRANSFER_COMPANY_NAME { get; set; }
        public string TRANSFER_DEPT { get; set; }
        public string IS_PAY_SUBSIST { get; set; }
        public Nullable<System.DateTime> PLAN_DESPATCH_DT { get; set; }
        public Nullable<System.DateTime> BACK_SCHOOL_DT { get; set; }
        public Nullable<System.DateTime> BACK_PLANT_DT { get; set; }
        public Nullable<System.DateTime> BE_CONTRACT_DT { get; set; }
        public Nullable<System.DateTime> BE_DESPATCH_DT { get; set; }
        public Nullable<System.DateTime> KEEP_DESPATCH_DT { get; set; }
        public Nullable<System.DateTime> BE_EMP_DT { get; set; }
        public Nullable<System.DateTime> RECENT_LEVEL_DT { get; set; }
        public Nullable<System.DateTime> RECENT_PJOB_DT { get; set; }
        public Nullable<System.DateTime> RECENT_DEPT_DT { get; set; }
        public Nullable<System.DateTime> RECENT_DIV_DT { get; set; }
        public string IS_MASTER { get; set; }
        public string DIRECT_HEAD_EMP_ID { get; set; }
        public string IS_UPD_HEAD { get; set; }
        public string OVERTIME_CTL_CD { get; set; }
        public string HEALTH_YEAR { get; set; }
        public string IS_DUTY_CHECK { get; set; }
        public string UNION_PJOB_CD { get; set; }
        public string MODEL_YEAR { get; set; }
        public string HONOR_YEAR { get; set; }
        public string NATION_CD { get; set; }
        public string JPN_CD { get; set; }
        public string LICENSE_ID { get; set; }
        public string PASSPORT_ID { get; set; }
        public string SEX_CD { get; set; }
        public Nullable<System.DateTime> BIRTH_DT { get; set; }
        public string BLOOD_TYPE { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal WEIGHT { get; set; }
        public string BIRTHPLACE { get; set; }
        public string ARMY_CD { get; set; }
        public string SALARY_ACCOUNT_BANK { get; set; }
        public string SALARY_ACCOUNT_BRANCH { get; set; }
        public string SALARY_ACCOUNT_NO { get; set; }
        public decimal RELATIVES { get; set; }
        public string INCOME_CD { get; set; }
        public string URGENT_CONTACT_NAME { get; set; }
        public string URGENT_CONTACT_RELATION { get; set; }
        public string URGENT_CONTACT_TEL { get; set; }
        public string REGISTER_ZIP_CD { get; set; }
        public string REGISTER_COUNTY { get; set; }
        public string REGISTER_REGION { get; set; }
        public string REGISTER_ADDR { get; set; }
        public string REGISTER_TEL { get; set; }
        public string CONTACT_ZIP_CD { get; set; }
        public string CONTACT_COUNTY { get; set; }
        public string CONTACT_REGION { get; set; }
        public string CONTACT_ADDR { get; set; }
        public string CONTACT_TEL { get; set; }
        public string MOBILE_TEL_1 { get; set; }
        public string MOBILE_TEL_2 { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string PERSONAL_EMAIL { get; set; }
        public string SALARY_EMAIL { get; set; }
        public string REMARK { get; set; }
        public string EDUCATION_CD { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string SALARY_EDUCATION_CD { get; set; }
        public string SALARY_GRADUATION_YEAR { get; set; }
        public decimal APPROVE_WORK_YEARS { get; set; }
        public string SALARY_EMAIL_CD { get; set; }
        public string EMP_NAME2 { get; set; }
    }
}
