//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_H_DEPT_DATA
    {
        public string DEPT_NO { get; set; }
        public string DEPT_NAME { get; set; }
        public string DEPT_SNAME { get; set; }
        public decimal DEPT_LEVEL { get; set; }
        public string HEAD_EMP_ID { get; set; }
        public string HEAD_EMP_NAME { get; set; }
        public string UP_DEPT_NO { get; set; }
        public string UP_DEPT_NAME { get; set; }
        public string ACC_CD { get; set; }
        public string ACC_DEPT_NO { get; set; }
        public string ACC_DEPT_NAME { get; set; }
        public string CAR_TYPE { get; set; }
        public string COST_DEPT_NO { get; set; }
        public string BUDGET_DEPT_NO { get; set; }
        public string DEPT_FULL_NAME { get; set; }
        public string DIV_DEPT_FULL_NAME { get; set; }
        public string DEPT_NO_20 { get; set; }
        public string DEPT_NAME_20 { get; set; }
        public string DEPT_NO_30 { get; set; }
        public string DEPT_NAME_30 { get; set; }
        public string DEPT_NO_40 { get; set; }
        public string DEPT_NAME_40 { get; set; }
        public string DEPT_NO_50 { get; set; }
        public string DEPT_NAME_50 { get; set; }
        public string DEPT_NO_60 { get; set; }
        public string DEPT_NAME_60 { get; set; }
        public string DEPT_NO_70 { get; set; }
        public string DEPT_NAME_70 { get; set; }
    }
}
